### ISSUE TITLE
Benchmark errors out with a TypeError

### ISSUE THREAD

**Issue by skyschub** [fast-jsonapi/comparisons#13]
Attempting to run the benchmark using the instructions provided in the readme, I get the following TypeError:

```
Warming up --------------------------------------
          🐌...JSONAPI::Serializer   182.645k i/s -    184.459k times in 1.009935sTraceback (most recent call last):
	28: from /usr/local/bundle/bin/benchmark-driver:23:in `<main>'
	27: from /usr/local/bundle/bin/benchmark-driver:23:in `load'
	26: from /usr/local/bundle/gems/benchmark_driver-0.15.17/exe/benchmark-driver:144:in `<top (required)>'
	25: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner.rb:29:in `run'
	24: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner.rb:29:in `each'
	23: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner.rb:30:in `block in run'
	22: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner.rb:30:in `each'
	21: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner.rb:31:in `block (2 levels) in run'
	20: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner.rb:31:in `each'
	19: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner.rb:45:in `block (3 levels) in run'
	18: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner.rb:108:in `with_clean_env'
	17: from /usr/local/lib/ruby/2.7.0/bundler.rb:381:in `with_unbundled_env'
	16: from /usr/local/lib/ruby/2.7.0/bundler.rb:677:in `with_env'
	15: from /usr/local/lib/ruby/2.7.0/bundler.rb:381:in `block in with_unbundled_env'
	14: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner.rb:109:in `block in with_clean_env'
	13: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner.rb:46:in `block (4 levels) in run'
	12: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner/ips.rb:30:in `run'
	11: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/output.rb:68:in `with_warmup'
	10: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/output/compare.rb:16:in `with_warmup'
	 9: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/output/compare.rb:113:in `without_stdout_buffering'
	 8: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/output/compare.rb:19:in `block in with_warmup'
	 7: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner/ips.rb:31:in `block in run'
	 6: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner/ips.rb:31:in `map'
	 5: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/runner/ips.rb:34:in `block (2 levels) in run'
	 4: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/output.rb:78:in `with_job'
	 3: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/output/compare.rb:66:in `with_job'
	 2: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/output/compare.rb:102:in `show_durations'
	 1: from /usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/output/compare.rb:161:in `estimate_clock'
/usr/local/bundle/gems/benchmark_driver-0.15.17/lib/benchmark_driver/output/compare.rb:161:in `/': String can't be coerced into Integer (TypeError)
```

**Comment by skyschub** [comment]
I can get it to run if I start `benchmark_driver` with `--output=markdown`, so this is just the default `compare` erroring out, probably because it can't compare the `k`s or something.

**Comment by mediafinger** [comment]
I've just run them on my MacMini 2018

> (but please, don't ask me what the difference between all the very similar sounding cases is)

```
Warming up --------------------------------------
           ...JSONAPI::Serializer    67.639k i/s -     72.264k times in 1.068374s (14.78μs/i)
     ...JSONAPI::Serializer(many)     94.412 i/s -      99.000 times in 1.048596s (10.59ms/i)
  ...JSONAPI::Serializer(include)     21.200 i/s -      24.000 times in 1.132102s (47.17ms/i)
     ...JSONAPI::Serializer(deep)     21.795 i/s -      24.000 times in 1.101195s (45.88ms/i)
         active_model_serializers     1.869k i/s -      1.947k times in 1.041786s (535.07μs/i)
   active_model_serializers(many)      2.188 i/s -       3.000 times in 1.370816s (456.94ms/i)
active_model_serializers(include)      0.963 i/s -       1.000 times in 1.038639s (1.04s/i)
   active_model_serializers(deep)      2.361 i/s -       3.000 times in 1.270562s (423.52ms/i)
             jsonapi-serializable    21.696k i/s -     23.030k times in 1.061471s (46.09μs/i)
       jsonapi-serializable(many)     29.641 i/s -      30.000 times in 1.012117s (33.74ms/i)
    jsonapi-serializable(include)      8.200 i/s -       9.000 times in 1.097598s (121.96ms/i)
       jsonapi-serializable(deep)     16.927 i/s -      18.000 times in 1.063417s (59.08ms/i)
              jsonapi-serializers    31.229k i/s -     32.274k times in 1.033454s (32.02μs/i)
        jsonapi-serializers(many)     39.695 i/s -      40.000 times in 1.007691s (25.19ms/i)
     jsonapi-serializers(include)      9.340 i/s -      10.000 times in 1.070636s (107.06ms/i)
        jsonapi-serializers(deep)      9.320 i/s -      10.000 times in 1.072915s (107.29ms/i)
Calculating -------------------------------------
           ...JSONAPI::Serializer    67.067k i/s -    202.917k times in 3.025569s (14.91μs/i)
     ...JSONAPI::Serializer(many)     94.030 i/s -     283.000 times in 3.009686s (10.63ms/i)
  ...JSONAPI::Serializer(include)     21.373 i/s -      63.000 times in 2.947597s (46.79ms/i)
     ...JSONAPI::Serializer(deep)     20.521 i/s -      65.000 times in 3.167449s (48.73ms/i)
         active_model_serializers     1.881k i/s -      5.606k times in 2.980291s (531.63μs/i)
   active_model_serializers(many)      2.188 i/s -       6.000 times in 2.742698s (457.12ms/i)
active_model_serializers(include)      0.979 i/s -       2.000 times in 2.043007s (1.02s/i)
   active_model_serializers(deep)      2.698 i/s -       7.000 times in 2.594248s (370.61ms/i)
             jsonapi-serializable    24.478k i/s -     65.088k times in 2.659046s (40.85μs/i)
       jsonapi-serializable(many)     31.454 i/s -      88.000 times in 2.797737s (31.79ms/i)
    jsonapi-serializable(include)      7.896 i/s -      24.000 times in 3.039362s (126.64ms/i)
       jsonapi-serializable(deep)     13.116 i/s -      50.000 times in 3.812136s (76.24ms/i)
              jsonapi-serializers    31.192k i/s -     93.687k times in 3.003576s (32.06μs/i)
        jsonapi-serializers(many)     36.766 i/s -     119.000 times in 3.236712s (27.20ms/i)
     jsonapi-serializers(include)      9.140 i/s -      28.000 times in 3.063529s (109.41ms/i)
        jsonapi-serializers(deep)     10.875 i/s -      27.000 times in 2.482797s (91.96ms/i)

Comparison:
           ...JSONAPI::Serializer:     67067.4 i/s
              jsonapi-serializers:     31191.8 i/s - 2.15x  slower
             jsonapi-serializable:     24477.9 i/s - 2.74x  slower
         active_model_serializers:      1881.0 i/s - 35.65x  slower
     ...JSONAPI::Serializer(many):        94.0 i/s - 713.26x  slower
        jsonapi-serializers(many):        36.8 i/s - 1824.18x  slower
       jsonapi-serializable(many):        31.5 i/s - 2132.24x  slower
  ...JSONAPI::Serializer(include):        21.4 i/s - 3137.90x  slower
     ...JSONAPI::Serializer(deep):        20.5 i/s - 3268.19x  slower
       jsonapi-serializable(deep):        13.1 i/s - 5113.40x  slower
        jsonapi-serializers(deep):        10.9 i/s - 6167.21x  slower
     jsonapi-serializers(include):         9.1 i/s - 7337.96x  slower
    jsonapi-serializable(include):         7.9 i/s - 8493.42x  slower
   active_model_serializers(deep):         2.7 i/s - 24855.63x  slower
   active_model_serializers(many):         2.2 i/s - 30657.59x  slower
active_model_serializers(include):         1.0 i/s - 68509.55x  slower 🐌
```
